-- 숫자형 함수
-- ABS
SELECT ABS(-7), ABS(0), ABS(7.8)
  FROM DUAL;
  
-- CEIL, FLOOR  
SELECT CEIL(7.6), FLOOR(7.6)
  FROM DUAL;  
  
-- EXP, LN, LOG
SELECT EXP(5), LN(148.413159102576603421115580040552279624), LOG(10, 10000)
FROM DUAL; 

SELECT EXP(LN(5))
FROM DUAL; 


-- MOD, SIGN
SELECT MOD(17, 3), SIGN(-19), SIGN(0)
  FROM DUAL;
  
-- POWER, SQRT
SELECT POWER(2,3), SQRT(3)
  FROM DUAL;
  
-- ROUND, TRUNC
SELECT ROUND(3.545, 2), ROUND(3.545, 1), TRUNC(3.545, 2), TRUNC(3.545, 1)
  FROM DUAL; 
   
  
-- 문자형 함수
-- CONCAT
SELECT CONCAT('A', 'B'), 'A' || 'B' || 'C'
  FROM DUAL;
  
-- INITCAP, UPPER, LOWER
SELECT INITCAP('abc'), UPPER('abc'), LOWER('A나bC'), INITCAP('홍gildong')
  FROM DUAL;  
  
SELECT *
FROM employees
WHERE first_name = 'steven';  

SELECT *
FROM employees
WHERE UPPER(first_name) = 'STEVEN';

-- LPAD, RPAD
SELECT LPAD( 'SQL', 5, '*' ), RPAD('SQL', 5, '*')
  FROM DUAL;
  
SELECT employee_id, 
       phone_number,
       LPAD(phone_number, 20, ' ') phone_number2
FROM employees
ORDER BY 1;  
  
-- LTRIM, RTRIM
SELECT LTRIM('**SQL**', '*'), RTRIM('**SQL**', '*')
  FROM DUAL;  
  
-- SUBSTR
SELECT SUBSTR('ABCDEFG', 1, 2) FIRSTS
      ,SUBSTR('ABCDEFG', 0, 2) SECONDS
      ,SUBSTR('ABCDEFG', 3, 2) THIRDS
      ,SUBSTR('ABCDEFG', 3 )   FOURTHS
      ,SUBSTR('ABCDEFG', -3)   FIFTHS
      ,SUBSTR('ABCDEFG', -3, 2)  SIXTHS
  FROM DUAL;    
  
-- TRIM, ASCII, LENGTH, LENGTHB
SELECT TRIM(' AB C D '), ASCII('a'), LENGTH('A B C'), LENGTHB('A B 강')
  FROM DUAL;  
  
-- REPLACE
SELECT REPLACE('산은 산이요 물은 물이다', '산', '언덕')
  FROM DUAL;  
  
SELECT TRIM(' AB C D '), REPLACE(' AB C D ', ' ', '')
  FROM DUAL;    
  
-- INSTR
SELECT INSTR('ABCABCABC', 'C')
      ,INSTR('ABCABCABC', 'c')
      ,INSTR('ABCABCABC', 'C', 2)
      ,INSTR('ABCABCABC', 'C', 2, 2)
FROM DUAL;

-- 날짜형 함수
-- SYSDATE
SELECT SYSDATE
  FROM DUAL;
  
-- ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE, 1), ADD_MONTHS(SYSDATE, -1), ADD_MONTHS(SYSDATE, 0)
  FROM DUAL;  
  
-- MONTHS_BETWEEN
SELECT SYSDATE + 31
      ,SYSDATE - 31
      ,MONTHS_BETWEEN(SYSDATE + 31, SYSDATE )
      ,MONTHS_BETWEEN(SYSDATE - 31, SYSDATE )
FROM DUAL;
  
-- LAST_DAY, NEXT_DAY
SELECT LAST_DAY(SYSDATE)
      ,NEXT_DAY(SYSDATE, '금')
FROM DUAL ;  

-- ROUND
SELECT SYSDATE 
      ,ROUND(SYSDATE, 'YYYY') YEARS
      ,ROUND(SYSDATE, 'MM') MONTHS
      ,ROUND(SYSDATE, 'DD')   DAYS
      ,ROUND(SYSDATE, 'HH24')  HOURS24
      ,ROUND(SYSDATE, 'MI')    MINUTES
      ,ROUND(SYSDATE)          DEFAULTS
FROM DUAL ;  


-- TRUNC
SELECT SYSDATE 
      ,TRUNC(SYSDATE, 'YYYY') YEARS
      ,TRUNC(SYSDATE, 'MM') MONTHS
      ,TRUNC(SYSDATE, 'DD')   DAYS
      ,TRUNC(SYSDATE, 'HH24')  HOURS24
      ,TRUNC(SYSDATE, 'MI')    MINUTES
      ,TRUNC(SYSDATE)          DEFAULTS
FROM DUAL ;  

SELECT SYSDATE,
       SYSDATE + 1 nextday,
       SYSDATE - 1 previousday
  FROM DUAL;

